---
# tasks file for ansible-role-vormetric-agent/

- name: "Test Access to CipherTrust Manager (CTM)"
  ansible.builtin.uri:
    url: "https://{{ ctm_url }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when:
    - register_ctm is defined
    - register_ctm is boolean
    - register_ctm | bool

- name: "Test Access to Vormetric Data Security Manager (DSM)"
  ansible.builtin.uri:
    url: "https://{{ dsm_url }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when:
    - register_dsm is defined
    - register_dsm is boolean
    - register_dsm | bool

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from upgrade playbook"
  ansible.builtin.include_tasks: upgrade.yaml
  when:
    - upgrade is defined
    - upgrade | bool