---
# Upgrade tasks file for ansible-role-vormetric-agent

#- name: "Test if upgrade boolean variable is set correctly"
#  ansible.builtin.assert:
#    that:
#      - upgrade is defined
#      - upgrade is boolean
#    quiet: yes

- name: "Collect all configured GuardPoints"
  ansible.builtin.shell:
    cmd: "secfsd -status guard | awk '{ print $1 }' | tail -n+3"
  args:
    chdir: "/bin/"
  register: result

- name: "Set Facts for GuardPoints"
  ansible.builtin.set_fact:
    guardpoints: "{{ result.stdout_lines }}"
  when:
    - result is defined
    - result.failed is false

- name: "Check for open files in each GuardPoint"
  ansible.builtin.shell:
    cmd: "lsof | grep {{ item }}"
  register: lsof
  failed_when: lsof.rc == 0
  with_items: "{{ guardpoints }}"

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/vormetric/"
    state: directory

#- name: "Check if installer package already exist"
#  ansible.builtin.stat:
#    path: "/root/software/vormetric/{{ package_name }}"
#  register: package

#- name: "Download installer package from local repository"
#  ansible.builtin.get_url:
#    url: "{{ software_url }}/{{ package_name }}"
#    dest: "/root/software/vormetric/"
#    validate_certs: no
#    mode: '0770'
#  when:
#    - not package.stat.exists | bool

#- name: "Create temp folder in package directory"
#  ansible.builtin.file:
#    path: "/root/software/vormetric/temp/"
#    state: directory

#- name: "Upgrade Vormetric Agent"
#  ansible.builtin.command:
#    cmd: ./{{ package_name }} -u -y -t /root/software/vormetric/temp/
#  args:
#    chdir: "/root/software/vormetric/"